# Generated by Django 5.2 on 2026-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave_requests",
            name="remark",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="leave_requests",
            name="leave_type",
            field=models.CharField(default=None, max_length=60),
        ),
    ]
