# Generated by Django 5.2 on 2026-03-01 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_leave_requests_remark_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.IntegerField(auto_created=True)),
                ("name", models.CharField(default=None, max_length=200)),
                ("age", models.IntegerField(default=None)),
                ("position", models.CharField(default=None, max_length=100)),
                ("salary", models.IntegerField(default=None)),
                ("join_date", models.DateField(default=None)),
                ("terminate_date", models.DateField(default=None)),
                ("is_active", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
