# Generated by Django 5.2 on 2026-03-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="id",
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="join_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
