# Generated by Django 5.2 on 2026-03-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_employee_id_alter_employee_emp_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="terminate_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
